const os = require('os')
console.log("check system architecture:",os.arch())
console.log("check RAM space free(bytes):",os.freemem())
console.log(`check RAM space free(GB)${os.freemem()/1024/1024/1024}`)
console.log("check RAM total space(bytes):",os.totalmem())
console.log(`check RAM total space(GB)${os.totalmem()/1024/1024/1024}`)
console.log("check hostname:",os.hostname())
console.log("check platform:",os.platform())
console.log("check temp file view:",os.tmpdir())
console.log("check operating system type:",os.type())